<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="3" tests="7" name="REST API POST Test" time="6.967" errors="0" timestamp="20 Jan 2021 06:55:05 GMT">
  <testcase classname="POSTTest" name="addManyEmployeesTest" time="0.342">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;50000&amp;gt; but was:&amp;lt;10000&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<50000> but was:<10000>
	at POSTTest.addManyEmployeesTest(POSTTest.java:141)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="POSTTest" name="validPostTest" time="0.386"/>
  <testcase classname="POSTTest" name="InvalidIdPostTest" time="0.236"/>
  <testcase classname="POSTTest" name="RepeatedIDPostTest" time="0.264"/>
  <testcase classname="POSTTest" name="InvalidIDPostTest" time="0.156">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at POSTTest.InvalidIDPostTest(POSTTest.java:96)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.516"/>
  <testcase classname="POSTTest" name="InvalidNamePostTest" time="0.169">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at POSTTest.InvalidNamePostTest(POSTTest.java:117)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
</testsuite>
