<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="3" tests="7" name="REST API POST Test" time="5.915" errors="0" timestamp="20 Jan 2021 12:11:18 GMT">
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.185"/>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.179"/>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.216"/>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.122">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.133">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.248">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;50000&amp;gt; but was:&amp;lt;10000&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<50000> but was:<10000>
	at POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:33)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.816"/>
</testsuite>
