<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="3" tests="7" name="REST API POST Test" time="6.523" errors="0" timestamp="21 Jan 2021 07:56:22 GMT">
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.431"/>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.438"/>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.412"/>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.206">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at Tests.POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:32)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="1.199">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at Tests.POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:32)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.458">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;50000&amp;gt; but was:&amp;lt;10000&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<50000> but was:<10000>
	at Tests.POSTTest.addManyEmployeesRepeatedIDTest(POSTTest.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="Tests.POSTTest" name="addManyEmployeesRepeatedIDTest" time="0.395"/>
</testsuite>
